In [1]:
import numpy as np

In [2]:
m=np.random.randint(1,10,(10,10))
print(m)

[[8 1 5 9 6 1 7 4 8 3]
 [7 8 4 3 9 1 6 3 5 9]
 [8 4 1 1 6 1 7 6 1 4]
 [1 6 6 1 2 6 9 9 6 4]
 [8 2 8 4 5 1 6 3 8 5]
 [2 7 5 1 1 5 6 4 6 2]
 [2 9 9 5 4 2 7 1 2 8]
 [7 3 4 8 9 3 2 2 9 9]
 [9 9 2 3 7 4 3 8 2 2]
 [9 3 9 8 9 7 2 4 1 7]]


In [4]:
print(m[0,0])
print(m[0,-1])
print(m[-1,0])
print(m[-1,-1])

8
3
9
7


In [5]:
print(m[0]) # first row
print(m[1]) # second row
print(m[-1]) # last row
print(m[:3]) # first 3 rows
print(m[-3:]) #last 3 rows





[8 1 5 9 6 1 7 4 8 3]
[7 8 4 3 9 1 6 3 5 9]
[9 3 9 8 9 7 2 4 1 7]
[[8 1 5 9 6 1 7 4 8 3]
 [7 8 4 3 9 1 6 3 5 9]
 [8 4 1 1 6 1 7 6 1 4]]
[[7 3 4 8 9 3 2 2 9 9]
 [9 9 2 3 7 4 3 8 2 2]
 [9 3 9 8 9 7 2 4 1 7]]


In [7]:
print(m[:,0])
print(m[:,-1])
print(m[:,:3])
print(m[:,-3:])



[8 7 8 1 8 2 2 7 9 9]
[3 9 4 4 5 2 8 9 2 7]
[[8 1 5]
 [7 8 4]
 [8 4 1]
 [1 6 6]
 [8 2 8]
 [2 7 5]
 [2 9 9]
 [7 3 4]
 [9 9 2]
 [9 3 9]]
[[4 8 3]
 [3 5 9]
 [6 1 4]
 [9 6 4]
 [3 8 5]
 [4 6 2]
 [1 2 8]
 [2 9 9]
 [8 2 2]
 [4 1 7]]


In [8]:
print(m[:,[0,2,3,5]])

[[8 5 9 1]
 [7 4 3 1]
 [8 1 1 1]
 [1 6 1 6]
 [8 8 4 1]
 [2 5 1 5]
 [2 9 5 2]
 [7 4 8 3]
 [9 2 3 4]
 [9 9 8 7]]


# filtering

In [10]:
m<5 #boolean filter

array([[False,  True, False, False, False,  True, False,  True, False,
         True],
       [False, False,  True,  True, False,  True, False,  True, False,
        False],
       [False,  True,  True,  True, False,  True, False, False,  True,
         True],
       [ True, False, False,  True,  True, False, False, False, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
        False],
       [ True, False, False,  True,  True, False, False,  True, False,
         True],
       [ True, False, False, False,  True,  True, False,  True,  True,
        False],
       [False,  True,  True, False, False,  True,  True,  True, False,
        False],
       [False, False,  True,  True, False,  True,  True, False,  True,
         True],
       [False,  True, False, False, False, False,  True,  True,  True,
        False]])

In [11]:
m[m<5]

array([1, 1, 4, 3, 4, 3, 1, 3, 4, 1, 1, 1, 1, 4, 1, 1, 2, 4, 2, 4, 1, 3,
       2, 1, 1, 4, 2, 2, 4, 2, 1, 2, 3, 4, 3, 2, 2, 2, 3, 4, 3, 2, 2, 3,
       2, 4, 1])

In [12]:
m[m>3]

array([8, 5, 9, 6, 7, 4, 8, 7, 8, 4, 9, 6, 5, 9, 8, 4, 6, 7, 6, 4, 6, 6,
       6, 9, 9, 6, 4, 8, 8, 4, 5, 6, 8, 5, 7, 5, 5, 6, 4, 6, 9, 9, 5, 4,
       7, 8, 7, 4, 8, 9, 9, 9, 9, 9, 7, 4, 8, 9, 9, 8, 9, 7, 4, 7])

In [13]:
m[(m>=3) & (m<=6)]

array([5, 6, 4, 3, 4, 3, 6, 3, 5, 4, 6, 6, 4, 6, 6, 6, 6, 4, 4, 5, 6, 3,
       5, 5, 5, 6, 4, 6, 5, 4, 3, 4, 3, 3, 4, 3, 3, 4])

In [15]:
m.flatten?

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()